/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/sap/cap-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CAPApplications returns a CAPApplicationInformer.
	CAPApplications() TypedCAPApplicationInformer
	// CAPApplicationVersions returns a CAPApplicationVersionInformer.
	CAPApplicationVersions() TypedCAPApplicationVersionInformer
	// CAPTenants returns a CAPTenantInformer.
	CAPTenants() TypedCAPTenantInformer
	// CAPTenantOperations returns a CAPTenantOperationInformer.
	CAPTenantOperations() TypedCAPTenantOperationInformer
	// CAPTenantOutputs returns a CAPTenantOutputInformer.
	CAPTenantOutputs() TypedCAPTenantOutputInformer
	// ClusterDomains returns a ClusterDomainInformer.
	ClusterDomains() TypedClusterDomainInformer
	// Domains returns a DomainInformer.
	Domains() TypedDomainInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CAPApplications returns a TypedCAPApplicationInformer.
func (v *version) CAPApplications() TypedCAPApplicationInformer {
	return &cAPApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CAPApplicationVersions returns a TypedCAPApplicationVersionInformer.
func (v *version) CAPApplicationVersions() TypedCAPApplicationVersionInformer {
	return &cAPApplicationVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CAPTenants returns a TypedCAPTenantInformer.
func (v *version) CAPTenants() TypedCAPTenantInformer {
	return &cAPTenantInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CAPTenantOperations returns a TypedCAPTenantOperationInformer.
func (v *version) CAPTenantOperations() TypedCAPTenantOperationInformer {
	return &cAPTenantOperationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CAPTenantOutputs returns a TypedCAPTenantOutputInformer.
func (v *version) CAPTenantOutputs() TypedCAPTenantOutputInformer {
	return &cAPTenantOutputInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClusterDomains returns a TypedClusterDomainInformer.
func (v *version) ClusterDomains() TypedClusterDomainInformer {
	return &clusterDomainInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Domains returns a TypedDomainInformer.
func (v *version) Domains() TypedDomainInformer {
	return &domainInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
