/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apissmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	versioned "github.com/sap/cap-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sap/cap-operator/pkg/client/informers/externalversions/internalinterfaces"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/listers/sme.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SubscriptionInformer provides access to a shared informer and lister for
// Subscriptions. Prefer using the type-safe variant (see [TypedSubscriptionInformer]).
type SubscriptionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() smesapcomv1alpha1.SubscriptionLister
}

// TypedSubscriptionInformer provides access to a shared informer and lister for
// Subscriptions, including the type-safe TypedInformer variant.
// It is a superset of SubscriptionInformer.
type TypedSubscriptionInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() SubscriptionIndexInformer
	Lister() smesapcomv1alpha1.SubscriptionLister
}

// SubscriptionIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type SubscriptionIndexInformer cache.TypedSharedIndexInformer[*apissmesapcomv1alpha1.Subscription]

// SubscriptionHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Subscription.
type SubscriptionHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apissmesapcomv1alpha1.Subscription]

// SubscriptionDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Subscription.
type SubscriptionDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apissmesapcomv1alpha1.Subscription]

// SubscriptionFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Subscription.
type SubscriptionFilteringHandler = cache.TypedFilteringResourceEventHandler[*apissmesapcomv1alpha1.Subscription]

// SubscriptionIndexers is a specialization of [cache.TypedIndexers] for Subscription.
type SubscriptionIndexers = cache.TypedIndexers[*apissmesapcomv1alpha1.Subscription]

// DeletedSubscription is a specialization of [cache.DeletedObject] for Subscription.
type DeletedSubscription = cache.DeletedObject[*apissmesapcomv1alpha1.Subscription]

type subscriptionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSubscriptionInformer constructs a new informer for Subscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSubscriptionInformer]).
func NewSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedSubscriptionInformer constructs a new informer for Subscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers SubscriptionIndexers) SubscriptionIndexInformer {
	return NewTypedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredSubscriptionInformer constructs a new informer for Subscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredSubscriptionInformer]).
func NewFilteredSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredSubscriptionInformer constructs a new informer for Subscription type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredSubscriptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers SubscriptionIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) SubscriptionIndexInformer {
	return NewTypedSubscriptionInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewSubscriptionInformerWithOptions constructs a new informer for Subscription type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSubscriptionInformerWithOptions]).
func NewSubscriptionInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedSubscriptionInformerWithOptions(client, namespace, options)
}

// NewTypedSubscriptionInformerWithOptions constructs a new informer for Subscription type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSubscriptionInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) SubscriptionIndexInformer {
	gvr := schema.GroupVersionResource{Group: "sme.sap.com", Version: "v1alpha1", Resource: "subscriptions"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apissmesapcomv1alpha1.Subscription](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SmeV1alpha1().Subscriptions(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SmeV1alpha1().Subscriptions(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SmeV1alpha1().Subscriptions(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SmeV1alpha1().Subscriptions(namespace).Watch(ctx, opts)
			},
		}, client),
		&apissmesapcomv1alpha1.Subscription{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *subscriptionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedSubscriptionInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *subscriptionInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *subscriptionInformer) TypedInformer() SubscriptionIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissmesapcomv1alpha1.Subscription](f.factory.InformerFor(&apissmesapcomv1alpha1.Subscription{}, f.defaultInformer))
}

func (f *subscriptionInformer) Lister() smesapcomv1alpha1.SubscriptionLister {
	return smesapcomv1alpha1.NewSubscriptionLister(f.Informer().GetIndexer())
}

// ToTypedSubscriptionInformer converts an untyped informer into a TypedSubscriptionInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Subscription. If that is not the case, calling type-safe methods of the returned
// TypedSubscriptionInformer leads to runtime panics. A safer alternative is to pass
// around a TypedSubscriptionInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedSubscriptionInformer(informer SubscriptionInformer) TypedSubscriptionInformer {
	if informer, ok := informer.(TypedSubscriptionInformer); ok {
		return informer
	}
	return &subscriptionTypedInformerAdapter{informer}
}

type subscriptionTypedInformerAdapter struct {
	SubscriptionInformer
}

func (a *subscriptionTypedInformerAdapter) TypedInformer() SubscriptionIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissmesapcomv1alpha1.Subscription](a.Informer())
}

// ToSubscriptionIndexInformer converts an untyped informer into a SubscriptionIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Subscription. If that is not the case, calling type-safe methods of the returned
// SubscriptionIndexInformer leads to runtime panics. A safer alternative is to pass
// around a SubscriptionIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToSubscriptionIndexInformer(informer cache.SharedIndexInformer) SubscriptionIndexInformer {
	if informer, ok := informer.(SubscriptionIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apissmesapcomv1alpha1.Subscription](informer)
}
