/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
)

// CAPApplicationSpecApplyConfiguration represents a declarative configuration of the CAPApplicationSpec type for use
// with apply.
//
// Deprecated: sme.sap.com/v1alpha1 is replaced by sme.sap.com/v1alpha2, use the corresponding types/resources from v1alpha2.
// CAPApplicationSpec defines the desired state of CAPApplication
type CAPApplicationSpecApplyConfiguration struct {
	// Deprecated: sme.sap.com/v1alpha1 is replaced by sme.sap.com/v1alpha2, use the corresponding types/resources from v1alpha2.
	v1alpha2.CAPApplicationSpecApplyConfiguration `json:""`
	// Deprecated: Domains used by the application. Will be removed in future versions, use `DomainRefs` instead
	Domains *ApplicationDomainsApplyConfiguration `json:"domains,omitempty"`
	// Deprecated: SAP BTP Global Account Identifier where services are entitled for the current application
	// Will be removed soon, use ProviderSubaccountId instead
	GlobalAccountId *string `json:"globalAccountId,omitempty"`
}

// CAPApplicationSpecApplyConfiguration constructs a declarative configuration of the CAPApplicationSpec type for use with
// apply.
func CAPApplicationSpec() *CAPApplicationSpecApplyConfiguration {
	return &CAPApplicationSpecApplyConfiguration{}
}

// WithDomainRefs adds the given value to the DomainRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DomainRefs field.
func (b *CAPApplicationSpecApplyConfiguration) WithDomainRefs(values ...*v1alpha2.DomainRefApplyConfiguration) *CAPApplicationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDomainRefs")
		}
		b.CAPApplicationSpecApplyConfiguration.DomainRefs = append(b.CAPApplicationSpecApplyConfiguration.DomainRefs, *values[i])
	}
	return b
}

// WithProviderSubaccountId sets the ProviderSubaccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSubaccountId field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithProviderSubaccountId(value string) *CAPApplicationSpecApplyConfiguration {
	b.CAPApplicationSpecApplyConfiguration.ProviderSubaccountId = &value
	return b
}

// WithBTPAppName sets the BTPAppName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BTPAppName field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithBTPAppName(value string) *CAPApplicationSpecApplyConfiguration {
	b.CAPApplicationSpecApplyConfiguration.BTPAppName = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithProvider(value *v1alpha2.BTPTenantIdentificationApplyConfiguration) *CAPApplicationSpecApplyConfiguration {
	b.CAPApplicationSpecApplyConfiguration.Provider = value
	return b
}

// WithBTP sets the BTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BTP field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithBTP(value *v1alpha2.BTPApplyConfiguration) *CAPApplicationSpecApplyConfiguration {
	b.CAPApplicationSpecApplyConfiguration.BTP = value
	return b
}

// WithRolloutOnCredentialUpdate sets the RolloutOnCredentialUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RolloutOnCredentialUpdate field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithRolloutOnCredentialUpdate(value bool) *CAPApplicationSpecApplyConfiguration {
	b.CAPApplicationSpecApplyConfiguration.RolloutOnCredentialUpdate = &value
	return b
}

// WithDomains sets the Domains field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domains field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithDomains(value *ApplicationDomainsApplyConfiguration) *CAPApplicationSpecApplyConfiguration {
	b.Domains = value
	return b
}

// WithGlobalAccountId sets the GlobalAccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GlobalAccountId field is set to the value of the last call.
func (b *CAPApplicationSpecApplyConfiguration) WithGlobalAccountId(value string) *CAPApplicationSpecApplyConfiguration {
	b.GlobalAccountId = &value
	return b
}
