/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/cert-manager/cert-manager/pkg/apis/meta/v1"
)

// CertManagerApplyConfiguration represents a declarative configuration of the CertManager type for use
// with apply.
type CertManagerApplyConfiguration struct {
	// Issuer configuration for the certificate
	IssuerRef *v1.IssuerReference `json:"issuerRef,omitempty"`
}

// CertManagerApplyConfiguration constructs a declarative configuration of the CertManager type for use with
// apply.
func CertManager() *CertManagerApplyConfiguration {
	return &CertManagerApplyConfiguration{}
}

// WithIssuerRef sets the IssuerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerRef field is set to the value of the last call.
func (b *CertManagerApplyConfiguration) WithIssuerRef(value v1.IssuerReference) *CertManagerApplyConfiguration {
	b.IssuerRef = &value
	return b
}
