/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DomainReferenceApplyConfiguration represents a declarative configuration of the DomainReference type for use
// with apply.
type DomainReferenceApplyConfiguration struct {
	Kind *string `json:"kind,omitempty"`
	Name *string `json:"name,omitempty"`
}

// DomainReferenceApplyConfiguration constructs a declarative configuration of the DomainReference type for use with
// apply.
func DomainReference() *DomainReferenceApplyConfiguration {
	return &DomainReferenceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DomainReferenceApplyConfiguration) WithKind(value string) *DomainReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DomainReferenceApplyConfiguration) WithName(value string) *DomainReferenceApplyConfiguration {
	b.Name = &value
	return b
}
