/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HTTPCookieApplyConfiguration represents a declarative configuration of the HTTPCookie type for use
// with apply.
type HTTPCookieApplyConfiguration struct {
	// Name of the cookie.
	Name *string `json:"name,omitempty"`
	// Path to set for the cookie.
	Path *string `json:"path,omitempty"`
	// Lifetime of the cookie. If specified, a cookie with the TTL will be
	// generated if the cookie is not present. If the TTL is present and zero,
	// the generated cookie will be a session cookie.
	Ttl *v1.Duration `json:"ttl,omitempty"`
	// Additional attributes for the cookie. They will be used when generating a new cookie.
	Attributes []NameValueApplyConfiguration `json:"attributes,omitempty"`
}

// HTTPCookieApplyConfiguration constructs a declarative configuration of the HTTPCookie type for use with
// apply.
func HTTPCookie() *HTTPCookieApplyConfiguration {
	return &HTTPCookieApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HTTPCookieApplyConfiguration) WithName(value string) *HTTPCookieApplyConfiguration {
	b.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *HTTPCookieApplyConfiguration) WithPath(value string) *HTTPCookieApplyConfiguration {
	b.Path = &value
	return b
}

// WithTtl sets the Ttl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ttl field is set to the value of the last call.
func (b *HTTPCookieApplyConfiguration) WithTtl(value v1.Duration) *HTTPCookieApplyConfiguration {
	b.Ttl = &value
	return b
}

// WithAttributes adds the given value to the Attributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attributes field.
func (b *HTTPCookieApplyConfiguration) WithAttributes(values ...*NameValueApplyConfiguration) *HTTPCookieApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttributes")
		}
		b.Attributes = append(b.Attributes, *values[i])
	}
	return b
}
