/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
)

// MetricRuleApplyConfiguration represents a declarative configuration of the MetricRule type for use
// with apply.
//
// MetricRule specifies a Prometheus metric and rule which represents a cleanup condition. Metrics of type Gauge and Counter are supported.
//
// Rule evaluation for Gauge type metric: The time series data of the metric (restricted to the current workload by setting `job` label as workload service name) is calculated as an average over the specified period.
// A sum of the calculated average from different time series is then compared to the provided threshold value to determine whether the rule has been satisfied.
// Evaluation: `sum(avg_over_time(<gauge-metric>{job=<workload-service-name>}[<lookback-duration>])) <= <lower0threshold-value>`
//
// Rule evaluation for Counter type metric: The time series data of the metric (restricted to the current workload by setting `job` label as workload service name) is calculated as rate of increase over the specified period.
// The sum of the calculated rates from different time series is then compared to the provided threshold value to determine whether the rule has been satisfied.
// Evaluation: `sum(rate(<counter-metric>{job=<workload-service-name>}[<lookback-duration>])) <= <lower0threshold-value>`
type MetricRuleApplyConfiguration struct {
	// Prometheus metric. For example `http_request_count`
	Name *string `json:"name,omitempty"`
	// Type of Prometheus metric which can be either `Gauge` or `Counter`
	Type *smesapcomv1alpha1.MetricType `json:"type,omitempty"`
	// Duration of time series data used for the rule evaluation
	CalculationPeriod *smesapcomv1alpha1.Duration `json:"calculationPeriod,omitempty"`
	// The threshold value which is compared against the calculated value. If calculated value is less than or equal to the threshold the rule condition is fulfilled.
	ThresholdValue *string `json:"thresholdValue,omitempty"`
}

// MetricRuleApplyConfiguration constructs a declarative configuration of the MetricRule type for use with
// apply.
func MetricRule() *MetricRuleApplyConfiguration {
	return &MetricRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MetricRuleApplyConfiguration) WithName(value string) *MetricRuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *MetricRuleApplyConfiguration) WithType(value smesapcomv1alpha1.MetricType) *MetricRuleApplyConfiguration {
	b.Type = &value
	return b
}

// WithCalculationPeriod sets the CalculationPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CalculationPeriod field is set to the value of the last call.
func (b *MetricRuleApplyConfiguration) WithCalculationPeriod(value smesapcomv1alpha1.Duration) *MetricRuleApplyConfiguration {
	b.CalculationPeriod = &value
	return b
}

// WithThresholdValue sets the ThresholdValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ThresholdValue field is set to the value of the last call.
func (b *MetricRuleApplyConfiguration) WithThresholdValue(value string) *MetricRuleApplyConfiguration {
	b.ThresholdValue = &value
	return b
}
