/*
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PodDisruptionBudgetApplyConfiguration represents a declarative configuration of the PodDisruptionBudget type for use
// with apply.
type PodDisruptionBudgetApplyConfiguration struct {
	MinAvailable *int32 `json:"minAvailable,omitempty"`
}

// PodDisruptionBudgetApplyConfiguration constructs a declarative configuration of the PodDisruptionBudget type for use with
// apply.
func PodDisruptionBudget() *PodDisruptionBudgetApplyConfiguration {
	return &PodDisruptionBudgetApplyConfiguration{}
}

// WithMinAvailable sets the MinAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAvailable field is set to the value of the last call.
func (b *PodDisruptionBudgetApplyConfiguration) WithMinAvailable(value int32) *PodDisruptionBudgetApplyConfiguration {
	b.MinAvailable = &value
	return b
}
