/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RouteApplyConfiguration represents a declarative configuration of the Route type for use
// with apply.
//
// Routing configuration (http match) for the exposed service
type RouteApplyConfiguration struct {
	// Name of the workload (eventually a service to route requests to); must be a valid workload name (Deployment)
	WorkloadName *string `json:"workloadName,omitempty"`
	// Port number used for the service (must be present in the workload/service)
	Port *int32 `json:"port,omitempty"`
	// A unique routing path used (as a match/prefix) to route requests to the workload (when omitted, "/" would be used)
	Path *string `json:"path,omitempty"`
}

// RouteApplyConfiguration constructs a declarative configuration of the Route type for use with
// apply.
func Route() *RouteApplyConfiguration {
	return &RouteApplyConfiguration{}
}

// WithWorkloadName sets the WorkloadName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadName field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithWorkloadName(value string) *RouteApplyConfiguration {
	b.WorkloadName = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithPort(value int32) *RouteApplyConfiguration {
	b.Port = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithPath(value string) *RouteApplyConfiguration {
	b.Path = &value
	return b
}
