/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceExposureApplyConfiguration represents a declarative configuration of the ServiceExposure type for use
// with apply.
type ServiceExposureApplyConfiguration struct {
	ExposedDomain *string `json:"exposedDomain,omitempty"`
}

// ServiceExposureApplyConfiguration constructs a declarative configuration of the ServiceExposure type for use with
// apply.
func ServiceExposure() *ServiceExposureApplyConfiguration {
	return &ServiceExposureApplyConfiguration{}
}

// WithExposedDomain sets the ExposedDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExposedDomain field is set to the value of the last call.
func (b *ServiceExposureApplyConfiguration) WithExposedDomain(value string) *ServiceExposureApplyConfiguration {
	b.ExposedDomain = &value
	return b
}
