/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StickinessHashApplyConfiguration represents a declarative configuration of the StickinessHash type for use
// with apply.
//
// Loosely based on the options available for consistent hash load balancer in istio (https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConsistentHashLB), but only include the options that make sense for our use case.
type StickinessHashApplyConfiguration struct {
	// Hash based on a specific HTTP header.
	HttpHeaderName *string `json:"httpHeaderName,omitempty"`
	// Hash based on HTTP cookie.
	HttpCookie *HTTPCookieApplyConfiguration `json:"httpCookie,omitempty"`
	// Hash based on the source IP address.
	// This is applicable for both TCP and HTTP connections.
	UseSourceIp *bool `json:"useSourceIp,omitempty"`
	// Hash based on a specific HTTP query parameter.
	HttpQueryParameterName *string `json:"httpQueryParameterName,omitempty"`
}

// StickinessHashApplyConfiguration constructs a declarative configuration of the StickinessHash type for use with
// apply.
func StickinessHash() *StickinessHashApplyConfiguration {
	return &StickinessHashApplyConfiguration{}
}

// WithHttpHeaderName sets the HttpHeaderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HttpHeaderName field is set to the value of the last call.
func (b *StickinessHashApplyConfiguration) WithHttpHeaderName(value string) *StickinessHashApplyConfiguration {
	b.HttpHeaderName = &value
	return b
}

// WithHttpCookie sets the HttpCookie field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HttpCookie field is set to the value of the last call.
func (b *StickinessHashApplyConfiguration) WithHttpCookie(value *HTTPCookieApplyConfiguration) *StickinessHashApplyConfiguration {
	b.HttpCookie = value
	return b
}

// WithUseSourceIp sets the UseSourceIp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseSourceIp field is set to the value of the last call.
func (b *StickinessHashApplyConfiguration) WithUseSourceIp(value bool) *StickinessHashApplyConfiguration {
	b.UseSourceIp = &value
	return b
}

// WithHttpQueryParameterName sets the HttpQueryParameterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HttpQueryParameterName field is set to the value of the last call.
func (b *StickinessHashApplyConfiguration) WithHttpQueryParameterName(value string) *StickinessHashApplyConfiguration {
	b.HttpQueryParameterName = &value
	return b
}
