/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StickinessApplyConfiguration represents a declarative configuration of the Stickiness type for use
// with apply.
type StickinessApplyConfiguration struct {
	// Hash based stickiness configuration.
	Hash *StickinessHashApplyConfiguration `json:"hash,omitempty"`
}

// StickinessApplyConfiguration constructs a declarative configuration of the Stickiness type for use with
// apply.
func Stickiness() *StickinessApplyConfiguration {
	return &StickinessApplyConfiguration{}
}

// WithHash sets the Hash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hash field is set to the value of the last call.
func (b *StickinessApplyConfiguration) WithHash(value *StickinessHashApplyConfiguration) *StickinessApplyConfiguration {
	b.Hash = value
	return b
}
