/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SubscriptionProviderStatusApplyConfiguration represents a declarative configuration of the SubscriptionProviderStatus type for use
// with apply.
type SubscriptionProviderStatusApplyConfiguration struct {
	GenericStatusApplyConfiguration `json:""`
	// State of the Domain
	State *smesapcomv1alpha1.SubscriptionProviderState `json:"state,omitempty"`
	// List of subscription dependencies discovered for the services specified in the spec
	Dependencies *string `json:"dependencies,omitempty"`
}

// SubscriptionProviderStatusApplyConfiguration constructs a declarative configuration of the SubscriptionProviderStatus type for use with
// apply.
func SubscriptionProviderStatus() *SubscriptionProviderStatusApplyConfiguration {
	return &SubscriptionProviderStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SubscriptionProviderStatusApplyConfiguration) WithObservedGeneration(value int64) *SubscriptionProviderStatusApplyConfiguration {
	b.GenericStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SubscriptionProviderStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SubscriptionProviderStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.GenericStatusApplyConfiguration.Conditions = append(b.GenericStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *SubscriptionProviderStatusApplyConfiguration) WithState(value smesapcomv1alpha1.SubscriptionProviderState) *SubscriptionProviderStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithDependencies sets the Dependencies field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dependencies field is set to the value of the last call.
func (b *SubscriptionProviderStatusApplyConfiguration) WithDependencies(value string) *SubscriptionProviderStatusApplyConfiguration {
	b.Dependencies = &value
	return b
}
