/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubscriptionInfoApplyConfiguration represents a declarative configuration of the SubscriptionInfo type for use
// with apply.
type SubscriptionInfoApplyConfiguration struct {
	// Type of Subscription (subscription-manager / saas-registry)
	Type *string `json:"type,omitempty"`
	// Name of the Subscription Credential
	SubscriptionSecret *string `json:"subscriptionSecret,omitempty"`
	// Name of the Auth Credential (Optional)
	AuthSecret *string `json:"authSecret,omitempty"`
}

// SubscriptionInfoApplyConfiguration constructs a declarative configuration of the SubscriptionInfo type for use with
// apply.
func SubscriptionInfo() *SubscriptionInfoApplyConfiguration {
	return &SubscriptionInfoApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SubscriptionInfoApplyConfiguration) WithType(value string) *SubscriptionInfoApplyConfiguration {
	b.Type = &value
	return b
}

// WithSubscriptionSecret sets the SubscriptionSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubscriptionSecret field is set to the value of the last call.
func (b *SubscriptionInfoApplyConfiguration) WithSubscriptionSecret(value string) *SubscriptionInfoApplyConfiguration {
	b.SubscriptionSecret = &value
	return b
}

// WithAuthSecret sets the AuthSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSecret field is set to the value of the last call.
func (b *SubscriptionInfoApplyConfiguration) WithAuthSecret(value string) *SubscriptionInfoApplyConfiguration {
	b.AuthSecret = &value
	return b
}
