/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubscriptionSpecApplyConfiguration represents a declarative configuration of the SubscriptionSpec type for use
// with apply.
type SubscriptionSpecApplyConfiguration struct {
	// Name of the application that is being subscribed to
	AppName *string `json:"appName,omitempty"`
	// Provider subaccount ID of the application that is being subscribed to (used to identify the owning CAPApplication)
	ProviderSubaccountId *string `json:"providerSubaccountId,omitempty"`
	// TenantId of the consumer subaccount subscribing to the application
	TenantId *string `json:"tenantId,omitempty"`
	// SubscriptionGuid of the subscription
	SubscriptionGuid *string `json:"subscriptionGuid,omitempty"`
	// Payload of the subscription request (JSON string).
	SubscriptionRequestPayload *string `json:"subscriptionRequestPayload,omitempty"`
}

// SubscriptionSpecApplyConfiguration constructs a declarative configuration of the SubscriptionSpec type for use with
// apply.
func SubscriptionSpec() *SubscriptionSpecApplyConfiguration {
	return &SubscriptionSpecApplyConfiguration{}
}

// WithAppName sets the AppName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppName field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithAppName(value string) *SubscriptionSpecApplyConfiguration {
	b.AppName = &value
	return b
}

// WithProviderSubaccountId sets the ProviderSubaccountId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSubaccountId field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithProviderSubaccountId(value string) *SubscriptionSpecApplyConfiguration {
	b.ProviderSubaccountId = &value
	return b
}

// WithTenantId sets the TenantId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantId field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithTenantId(value string) *SubscriptionSpecApplyConfiguration {
	b.TenantId = &value
	return b
}

// WithSubscriptionGuid sets the SubscriptionGuid field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubscriptionGuid field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithSubscriptionGuid(value string) *SubscriptionSpecApplyConfiguration {
	b.SubscriptionGuid = &value
	return b
}

// WithSubscriptionRequestPayload sets the SubscriptionRequestPayload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubscriptionRequestPayload field is set to the value of the last call.
func (b *SubscriptionSpecApplyConfiguration) WithSubscriptionRequestPayload(value string) *SubscriptionSpecApplyConfiguration {
	b.SubscriptionRequestPayload = &value
	return b
}
