/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SubscriptionStatusApplyConfiguration represents a declarative configuration of the SubscriptionStatus type for use
// with apply.
type SubscriptionStatusApplyConfiguration struct {
	GenericStatusApplyConfiguration `json:",inline"`
	// State of the Domain
	State *smesapcomv1alpha1.SubscriptionState `json:"state,omitempty"`
	// Tenant specific URL of the subscribed application
	Url *string `json:"url,omitempty"`
}

// SubscriptionStatusApplyConfiguration constructs a declarative configuration of the SubscriptionStatus type for use with
// apply.
func SubscriptionStatus() *SubscriptionStatusApplyConfiguration {
	return &SubscriptionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SubscriptionStatusApplyConfiguration) WithObservedGeneration(value int64) *SubscriptionStatusApplyConfiguration {
	b.GenericStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SubscriptionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SubscriptionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.GenericStatusApplyConfiguration.Conditions = append(b.GenericStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *SubscriptionStatusApplyConfiguration) WithState(value smesapcomv1alpha1.SubscriptionState) *SubscriptionStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *SubscriptionStatusApplyConfiguration) WithUrl(value string) *SubscriptionStatusApplyConfiguration {
	b.Url = &value
	return b
}
