/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubscriptionProviderSpecApplyConfiguration represents a declarative configuration of the SubscriptionProviderSpec type for use
// with apply.
type SubscriptionProviderSpecApplyConfiguration struct {
	// Name of the application that is being subscribed to
	AppName *string `json:"appName,omitempty"`
	// Provider subaccount ID for the application that is being subscribed to
	ProviderSubaccountID *string `json:"providerSubaccountId,omitempty"`
	// The secret(s) containing the subscription credentials that are necessary to create a subscription for the application (Fetched from the same namespace as this resource).
	SubscriptionInfo *SubscriptionInfoApplyConfiguration `json:"subscriptionInfo,omitempty"`
}

// SubscriptionProviderSpecApplyConfiguration constructs a declarative configuration of the SubscriptionProviderSpec type for use with
// apply.
func SubscriptionProviderSpec() *SubscriptionProviderSpecApplyConfiguration {
	return &SubscriptionProviderSpecApplyConfiguration{}
}

// WithAppName sets the AppName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppName field is set to the value of the last call.
func (b *SubscriptionProviderSpecApplyConfiguration) WithAppName(value string) *SubscriptionProviderSpecApplyConfiguration {
	b.AppName = &value
	return b
}

// WithProviderSubaccountID sets the ProviderSubaccountID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSubaccountID field is set to the value of the last call.
func (b *SubscriptionProviderSpecApplyConfiguration) WithProviderSubaccountID(value string) *SubscriptionProviderSpecApplyConfiguration {
	b.ProviderSubaccountID = &value
	return b
}

// WithSubscriptionInfo sets the SubscriptionInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubscriptionInfo field is set to the value of the last call.
func (b *SubscriptionProviderSpecApplyConfiguration) WithSubscriptionInfo(value *SubscriptionInfoApplyConfiguration) *SubscriptionProviderSpecApplyConfiguration {
	b.SubscriptionInfo = value
	return b
}
