/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// WorkloadMonitoringApplyConfiguration represents a declarative configuration of the WorkloadMonitoring type for use
// with apply.
type WorkloadMonitoringApplyConfiguration struct {
	DeletionRules *DeletionRulesApplyConfiguration    `json:"deletionRules,omitempty"`
	ScrapeConfig  *MonitoringConfigApplyConfiguration `json:"scrapeConfig,omitempty"`
}

// WorkloadMonitoringApplyConfiguration constructs a declarative configuration of the WorkloadMonitoring type for use with
// apply.
func WorkloadMonitoring() *WorkloadMonitoringApplyConfiguration {
	return &WorkloadMonitoringApplyConfiguration{}
}

// WithDeletionRules sets the DeletionRules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionRules field is set to the value of the last call.
func (b *WorkloadMonitoringApplyConfiguration) WithDeletionRules(value *DeletionRulesApplyConfiguration) *WorkloadMonitoringApplyConfiguration {
	b.DeletionRules = value
	return b
}

// WithScrapeConfig sets the ScrapeConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScrapeConfig field is set to the value of the last call.
func (b *WorkloadMonitoringApplyConfiguration) WithScrapeConfig(value *MonitoringConfigApplyConfiguration) *WorkloadMonitoringApplyConfiguration {
	b.ScrapeConfig = value
	return b
}
