/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	applyconfigurationsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	scheme "github.com/sap/cap-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CAPApplicationVersionsGetter has a method to return a CAPApplicationVersionInterface.
// A group's client should implement this interface.
type CAPApplicationVersionsGetter interface {
	CAPApplicationVersions(namespace string) CAPApplicationVersionInterface
}

// CAPApplicationVersionInterface has methods to work with CAPApplicationVersion resources.
type CAPApplicationVersionInterface interface {
	Create(ctx context.Context, cAPApplicationVersion *smesapcomv1alpha2.CAPApplicationVersion, opts v1.CreateOptions) (*smesapcomv1alpha2.CAPApplicationVersion, error)
	Update(ctx context.Context, cAPApplicationVersion *smesapcomv1alpha2.CAPApplicationVersion, opts v1.UpdateOptions) (*smesapcomv1alpha2.CAPApplicationVersion, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cAPApplicationVersion *smesapcomv1alpha2.CAPApplicationVersion, opts v1.UpdateOptions) (*smesapcomv1alpha2.CAPApplicationVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*smesapcomv1alpha2.CAPApplicationVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*smesapcomv1alpha2.CAPApplicationVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *smesapcomv1alpha2.CAPApplicationVersion, err error)
	Apply(ctx context.Context, cAPApplicationVersion *applyconfigurationsmesapcomv1alpha2.CAPApplicationVersionApplyConfiguration, opts v1.ApplyOptions) (result *smesapcomv1alpha2.CAPApplicationVersion, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, cAPApplicationVersion *applyconfigurationsmesapcomv1alpha2.CAPApplicationVersionApplyConfiguration, opts v1.ApplyOptions) (result *smesapcomv1alpha2.CAPApplicationVersion, err error)
	CAPApplicationVersionExpansion
}

// cAPApplicationVersions implements CAPApplicationVersionInterface
type cAPApplicationVersions struct {
	*gentype.ClientWithListAndApply[*smesapcomv1alpha2.CAPApplicationVersion, *smesapcomv1alpha2.CAPApplicationVersionList, *applyconfigurationsmesapcomv1alpha2.CAPApplicationVersionApplyConfiguration]
}

// newCAPApplicationVersions returns a CAPApplicationVersions
func newCAPApplicationVersions(c *SmeV1alpha2Client, namespace string) *cAPApplicationVersions {
	return &cAPApplicationVersions{
		gentype.NewClientWithListAndApply[*smesapcomv1alpha2.CAPApplicationVersion, *smesapcomv1alpha2.CAPApplicationVersionList, *applyconfigurationsmesapcomv1alpha2.CAPApplicationVersionApplyConfiguration](
			"capapplicationversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *smesapcomv1alpha2.CAPApplicationVersion { return &smesapcomv1alpha2.CAPApplicationVersion{} },
			func() *smesapcomv1alpha2.CAPApplicationVersionList {
				return &smesapcomv1alpha2.CAPApplicationVersionList{}
			},
		),
	}
}
