/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	typedsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterDomains implements ClusterDomainInterface
type fakeClusterDomains struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterDomain, *v1alpha1.ClusterDomainList, *smesapcomv1alpha1.ClusterDomainApplyConfiguration]
	Fake *FakeSmeV1alpha1
}

func newFakeClusterDomains(fake *FakeSmeV1alpha1, namespace string) typedsmesapcomv1alpha1.ClusterDomainInterface {
	return &fakeClusterDomains{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterDomain, *v1alpha1.ClusterDomainList, *smesapcomv1alpha1.ClusterDomainApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clusterdomains"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterDomain"),
			func() *v1alpha1.ClusterDomain { return &v1alpha1.ClusterDomain{} },
			func() *v1alpha1.ClusterDomainList { return &v1alpha1.ClusterDomainList{} },
			func(dst, src *v1alpha1.ClusterDomainList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterDomainList) []*v1alpha1.ClusterDomain {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterDomainList, items []*v1alpha1.ClusterDomain) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
