/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	typedsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCAPApplications implements CAPApplicationInterface
type fakeCAPApplications struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.CAPApplication, *v1alpha1.CAPApplicationList, *smesapcomv1alpha1.CAPApplicationApplyConfiguration]
	Fake *FakeSmeV1alpha1
}

func newFakeCAPApplications(fake *FakeSmeV1alpha1, namespace string) typedsmesapcomv1alpha1.CAPApplicationInterface {
	return &fakeCAPApplications{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.CAPApplication, *v1alpha1.CAPApplicationList, *smesapcomv1alpha1.CAPApplicationApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("capapplications"),
			v1alpha1.SchemeGroupVersion.WithKind("CAPApplication"),
			func() *v1alpha1.CAPApplication { return &v1alpha1.CAPApplication{} },
			func() *v1alpha1.CAPApplicationList { return &v1alpha1.CAPApplicationList{} },
			func(dst, src *v1alpha1.CAPApplicationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CAPApplicationList) []*v1alpha1.CAPApplication {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CAPApplicationList, items []*v1alpha1.CAPApplication) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
