/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	typedsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCAPApplicationVersions implements CAPApplicationVersionInterface
type fakeCAPApplicationVersions struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.CAPApplicationVersion, *v1alpha1.CAPApplicationVersionList, *smesapcomv1alpha1.CAPApplicationVersionApplyConfiguration]
	Fake *FakeSmeV1alpha1
}

func newFakeCAPApplicationVersions(fake *FakeSmeV1alpha1, namespace string) typedsmesapcomv1alpha1.CAPApplicationVersionInterface {
	return &fakeCAPApplicationVersions{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.CAPApplicationVersion, *v1alpha1.CAPApplicationVersionList, *smesapcomv1alpha1.CAPApplicationVersionApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("capapplicationversions"),
			v1alpha1.SchemeGroupVersion.WithKind("CAPApplicationVersion"),
			func() *v1alpha1.CAPApplicationVersion { return &v1alpha1.CAPApplicationVersion{} },
			func() *v1alpha1.CAPApplicationVersionList { return &v1alpha1.CAPApplicationVersionList{} },
			func(dst, src *v1alpha1.CAPApplicationVersionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CAPApplicationVersionList) []*v1alpha1.CAPApplicationVersion {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CAPApplicationVersionList, items []*v1alpha1.CAPApplicationVersion) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
