/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	typedsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubscriptionProviders implements SubscriptionProviderInterface
type fakeSubscriptionProviders struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.SubscriptionProvider, *v1alpha1.SubscriptionProviderList, *smesapcomv1alpha1.SubscriptionProviderApplyConfiguration]
	Fake *FakeSmeV1alpha1
}

func newFakeSubscriptionProviders(fake *FakeSmeV1alpha1, namespace string) typedsmesapcomv1alpha1.SubscriptionProviderInterface {
	return &fakeSubscriptionProviders{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.SubscriptionProvider, *v1alpha1.SubscriptionProviderList, *smesapcomv1alpha1.SubscriptionProviderApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subscriptionproviders"),
			v1alpha1.SchemeGroupVersion.WithKind("SubscriptionProvider"),
			func() *v1alpha1.SubscriptionProvider { return &v1alpha1.SubscriptionProvider{} },
			func() *v1alpha1.SubscriptionProviderList { return &v1alpha1.SubscriptionProviderList{} },
			func(dst, src *v1alpha1.SubscriptionProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubscriptionProviderList) []*v1alpha1.SubscriptionProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SubscriptionProviderList, items []*v1alpha1.SubscriptionProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
