/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	typedsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubscriptions implements SubscriptionInterface
type fakeSubscriptions struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Subscription, *v1alpha1.SubscriptionList, *smesapcomv1alpha1.SubscriptionApplyConfiguration]
	Fake *FakeSmeV1alpha1
}

func newFakeSubscriptions(fake *FakeSmeV1alpha1, namespace string) typedsmesapcomv1alpha1.SubscriptionInterface {
	return &fakeSubscriptions{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Subscription, *v1alpha1.SubscriptionList, *smesapcomv1alpha1.SubscriptionApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subscriptions"),
			v1alpha1.SchemeGroupVersion.WithKind("Subscription"),
			func() *v1alpha1.Subscription { return &v1alpha1.Subscription{} },
			func() *v1alpha1.SubscriptionList { return &v1alpha1.SubscriptionList{} },
			func(dst, src *v1alpha1.SubscriptionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubscriptionList) []*v1alpha1.Subscription {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SubscriptionList, items []*v1alpha1.Subscription) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
