/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	scheme "github.com/sap/cap-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CAPTenantOutputsGetter has a method to return a CAPTenantOutputInterface.
// A group's client should implement this interface.
type CAPTenantOutputsGetter interface {
	CAPTenantOutputs(namespace string) CAPTenantOutputInterface
}

// CAPTenantOutputInterface has methods to work with CAPTenantOutput resources.
type CAPTenantOutputInterface interface {
	Create(ctx context.Context, cAPTenantOutput *v1alpha1.CAPTenantOutput, opts v1.CreateOptions) (*v1alpha1.CAPTenantOutput, error)
	Update(ctx context.Context, cAPTenantOutput *v1alpha1.CAPTenantOutput, opts v1.UpdateOptions) (*v1alpha1.CAPTenantOutput, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CAPTenantOutput, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CAPTenantOutputList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CAPTenantOutput, err error)
	Apply(ctx context.Context, cAPTenantOutput *smesapcomv1alpha1.CAPTenantOutputApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.CAPTenantOutput, err error)
	CAPTenantOutputExpansion
}

// cAPTenantOutputs implements CAPTenantOutputInterface
type cAPTenantOutputs struct {
	client rest.Interface
	ns     string
}

// newCAPTenantOutputs returns a CAPTenantOutputs
func newCAPTenantOutputs(c *SmeV1alpha1Client, namespace string) *cAPTenantOutputs {
	return &cAPTenantOutputs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cAPTenantOutput, and returns the corresponding cAPTenantOutput object, and an error if there is any.
func (c *cAPTenantOutputs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CAPTenantOutput, err error) {
	result = &v1alpha1.CAPTenantOutput{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("captenantoutputs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CAPTenantOutputs that match those selectors.
func (c *cAPTenantOutputs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CAPTenantOutputList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CAPTenantOutputList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("captenantoutputs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cAPTenantOutputs.
func (c *cAPTenantOutputs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("captenantoutputs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cAPTenantOutput and creates it.  Returns the server's representation of the cAPTenantOutput, and an error, if there is any.
func (c *cAPTenantOutputs) Create(ctx context.Context, cAPTenantOutput *v1alpha1.CAPTenantOutput, opts v1.CreateOptions) (result *v1alpha1.CAPTenantOutput, err error) {
	result = &v1alpha1.CAPTenantOutput{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("captenantoutputs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cAPTenantOutput).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cAPTenantOutput and updates it. Returns the server's representation of the cAPTenantOutput, and an error, if there is any.
func (c *cAPTenantOutputs) Update(ctx context.Context, cAPTenantOutput *v1alpha1.CAPTenantOutput, opts v1.UpdateOptions) (result *v1alpha1.CAPTenantOutput, err error) {
	result = &v1alpha1.CAPTenantOutput{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("captenantoutputs").
		Name(cAPTenantOutput.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cAPTenantOutput).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cAPTenantOutput and deletes it. Returns an error if one occurs.
func (c *cAPTenantOutputs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("captenantoutputs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cAPTenantOutputs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("captenantoutputs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cAPTenantOutput.
func (c *cAPTenantOutputs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CAPTenantOutput, err error) {
	result = &v1alpha1.CAPTenantOutput{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("captenantoutputs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied cAPTenantOutput.
func (c *cAPTenantOutputs) Apply(ctx context.Context, cAPTenantOutput *smesapcomv1alpha1.CAPTenantOutputApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.CAPTenantOutput, err error) {
	if cAPTenantOutput == nil {
		return nil, fmt.Errorf("cAPTenantOutput provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(cAPTenantOutput)
	if err != nil {
		return nil, err
	}
	name := cAPTenantOutput.Name
	if name == nil {
		return nil, fmt.Errorf("cAPTenantOutput.Name must be provided to Apply")
	}
	result = &v1alpha1.CAPTenantOutput{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("captenantoutputs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
