/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	applyconfigurationsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	scheme "github.com/sap/cap-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterDomainsGetter has a method to return a ClusterDomainInterface.
// A group's client should implement this interface.
type ClusterDomainsGetter interface {
	ClusterDomains(namespace string) ClusterDomainInterface
}

// ClusterDomainInterface has methods to work with ClusterDomain resources.
type ClusterDomainInterface interface {
	Create(ctx context.Context, clusterDomain *smesapcomv1alpha1.ClusterDomain, opts v1.CreateOptions) (*smesapcomv1alpha1.ClusterDomain, error)
	Update(ctx context.Context, clusterDomain *smesapcomv1alpha1.ClusterDomain, opts v1.UpdateOptions) (*smesapcomv1alpha1.ClusterDomain, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterDomain *smesapcomv1alpha1.ClusterDomain, opts v1.UpdateOptions) (*smesapcomv1alpha1.ClusterDomain, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*smesapcomv1alpha1.ClusterDomain, error)
	List(ctx context.Context, opts v1.ListOptions) (*smesapcomv1alpha1.ClusterDomainList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *smesapcomv1alpha1.ClusterDomain, err error)
	Apply(ctx context.Context, clusterDomain *applyconfigurationsmesapcomv1alpha1.ClusterDomainApplyConfiguration, opts v1.ApplyOptions) (result *smesapcomv1alpha1.ClusterDomain, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterDomain *applyconfigurationsmesapcomv1alpha1.ClusterDomainApplyConfiguration, opts v1.ApplyOptions) (result *smesapcomv1alpha1.ClusterDomain, err error)
	ClusterDomainExpansion
}

// clusterDomains implements ClusterDomainInterface
type clusterDomains struct {
	*gentype.ClientWithListAndApply[*smesapcomv1alpha1.ClusterDomain, *smesapcomv1alpha1.ClusterDomainList, *applyconfigurationsmesapcomv1alpha1.ClusterDomainApplyConfiguration]
}

// newClusterDomains returns a ClusterDomains
func newClusterDomains(c *SmeV1alpha1Client, namespace string) *clusterDomains {
	return &clusterDomains{
		gentype.NewClientWithListAndApply[*smesapcomv1alpha1.ClusterDomain, *smesapcomv1alpha1.ClusterDomainList, *applyconfigurationsmesapcomv1alpha1.ClusterDomainApplyConfiguration](
			"clusterdomains",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *smesapcomv1alpha1.ClusterDomain { return &smesapcomv1alpha1.ClusterDomain{} },
			func() *smesapcomv1alpha1.ClusterDomainList { return &smesapcomv1alpha1.ClusterDomainList{} },
		),
	}
}
