/*
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type CAPApplicationExpansion interface{}

type CAPApplicationVersionExpansion interface{}

type CAPTenantExpansion interface{}

type CAPTenantOperationExpansion interface{}

type CAPTenantOutputExpansion interface{}
