/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	applyconfigurationsmesapcomv1alpha1 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha1"
	scheme "github.com/sap/cap-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubscriptionsGetter has a method to return a SubscriptionInterface.
// A group's client should implement this interface.
type SubscriptionsGetter interface {
	Subscriptions(namespace string) SubscriptionInterface
}

// SubscriptionInterface has methods to work with Subscription resources.
type SubscriptionInterface interface {
	Create(ctx context.Context, subscription *smesapcomv1alpha1.Subscription, opts v1.CreateOptions) (*smesapcomv1alpha1.Subscription, error)
	Update(ctx context.Context, subscription *smesapcomv1alpha1.Subscription, opts v1.UpdateOptions) (*smesapcomv1alpha1.Subscription, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subscription *smesapcomv1alpha1.Subscription, opts v1.UpdateOptions) (*smesapcomv1alpha1.Subscription, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*smesapcomv1alpha1.Subscription, error)
	List(ctx context.Context, opts v1.ListOptions) (*smesapcomv1alpha1.SubscriptionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *smesapcomv1alpha1.Subscription, err error)
	Apply(ctx context.Context, subscription *applyconfigurationsmesapcomv1alpha1.SubscriptionApplyConfiguration, opts v1.ApplyOptions) (result *smesapcomv1alpha1.Subscription, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, subscription *applyconfigurationsmesapcomv1alpha1.SubscriptionApplyConfiguration, opts v1.ApplyOptions) (result *smesapcomv1alpha1.Subscription, err error)
	SubscriptionExpansion
}

// subscriptions implements SubscriptionInterface
type subscriptions struct {
	*gentype.ClientWithListAndApply[*smesapcomv1alpha1.Subscription, *smesapcomv1alpha1.SubscriptionList, *applyconfigurationsmesapcomv1alpha1.SubscriptionApplyConfiguration]
}

// newSubscriptions returns a Subscriptions
func newSubscriptions(c *SmeV1alpha1Client, namespace string) *subscriptions {
	return &subscriptions{
		gentype.NewClientWithListAndApply[*smesapcomv1alpha1.Subscription, *smesapcomv1alpha1.SubscriptionList, *applyconfigurationsmesapcomv1alpha1.SubscriptionApplyConfiguration](
			"subscriptions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *smesapcomv1alpha1.Subscription { return &smesapcomv1alpha1.Subscription{} },
			func() *smesapcomv1alpha1.SubscriptionList { return &smesapcomv1alpha1.SubscriptionList{} },
		),
	}
}
