apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: capapplications.sme.sap.com
spec:
  scope: Namespaced
  names:
    plural: capapplications
    singular: capapplication
    kind: CAPApplication
    shortNames: ["ca"]
  group: sme.sap.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: State
          type: string
          jsonPath: .status.state
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required:
                ["btpAppName", "globalAccountId", "provider", "domains", "btp"]
              properties:
                btpAppName:
                  type: string
                globalAccountId:
                  type: string
                domains:
                  type: object
                  required: ["primary", "istioIngressGatewayLabels"]
                  properties:
                    primary:
                      type: string
                      pattern: "^[a-z0-9-.]+$"
                      maxLength: 62
                    secondary:
                      type: array
                      items:
                        type: string
                        pattern: "^[a-z0-9-.]+$"
                    dnsTarget:
                      type: string
                      pattern: "^[a-z0-9-.]*$"
                    istioIngressGatewayLabels:
                      type: array
                      items:
                        minItems: 1
                        type: object
                        required: ["name", "value"]
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                            minLength: 1
                provider:
                  type: object
                  required: ["subDomain", "tenantId"]
                  properties:
                    subDomain:
                      type: string
                    tenantId:
                      type: string
                btp:
                  type: "object"
                  required: ["services"]
                  properties:
                    services:
                      type: array
                      items:
                        type: object
                        required: ["class", "name", "secret"]
                        properties:
                          class:
                            type: string
                          name:
                            type: string
                          secret:
                            type: string
            status:
              type: object
              required: ["state"]
              default:
                state: ""
                observedGeneration: -1
              properties:
                observedGeneration:
                  type: integer
                state:
                  type: string
                  enum: ["", "Consistent", "Processing", "Error", "Deleting"]
                lastFullReconciliationTime:
                  type: string
                  format: datetime
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status"]
                    properties:
                      type:
                        type: string
                        enum: ["Ready", "AllTenantsReady", "LatestVersionReady"]
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastUpdateTime: # Unused property
                        type: string
                        format: datetime
                      lastTransitionTime:
                        type: string
                        format: datetime
                      reason:
                        type: string
                        minLength: 1
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                domainSpecHash:
                  type: string
