apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: captenantoperations.sme.sap.com
spec:
  scope: Namespaced
  names:
    plural: captenantoperations
    singular: captenantoperation
    kind: CAPTenantOperation
    shortNames: ["ctop"]
  group: sme.sap.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: State
          type: string
          jsonPath: .status.state
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required:
                [
                  "operation",
                  "tenantId",
                  "subDomain",
                  "capApplicationVersionInstance",
                ]
              properties:
                operation:
                  type: string
                  enum: ["provisioning", "deprovisioning", "upgrade"]
                subDomain:
                  type: string
                tenantId:
                  type: string
                capApplicationVersionInstance:
                  type: string
                steps:
                  type: array
                  items:
                    type: object
                    required: ["name", "type"]
                    properties:
                      name:
                        type: string
                        pattern: "^[a-z]([-a-z0-9]*[a-z0-9])?$"
                      type:
                        type: string
                        enum: ["TenantOperation", "CustomTenantOperation"]
                      continueOnFailure:
                        type: boolean
            status:
              type: object
              required: ["state"]
              default:
                state: ""
                observedGeneration: -1
              properties:
                currentStep:
                  type: integer
                  format: int32
                  minimum: 0
                activeJob:
                  type: string
                observedGeneration:
                  type: integer
                state:
                  type: string
                  enum: ["", "Processing", "Completed", "Failed", "Deleting"]
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status"]
                    properties:
                      type:
                        type: string
                        enum: ["Ready"]
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastUpdateTime: # Unused property
                        type: string
                        format: datetime
                      lastTransitionTime:
                        type: string
                        format: datetime
                      reason:
                        type: string
                        minLength: 1
                      message:
                        type: string
                      observedGeneration:
                        type: integer
