apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: captenants.sme.sap.com
spec:
  scope: Namespaced
  names:
    plural: captenants
    singular: captenant
    kind: CAPTenant
    shortNames: ["cat"]
  group: sme.sap.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: State
          type: string
          jsonPath: .status.state
        - name: Current Version
          type: string
          jsonPath: .status.currentCAPApplicationVersionInstance
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["capApplicationInstance", "subDomain", "tenantId"]
              properties:
                capApplicationInstance:
                  type: string
                subDomain:
                  type: string
                tenantId:
                  type: string
                version:
                  type: string
                versionUpgradeStrategy:
                  default: "always"
                  type: string
                  enum: ["always", "never"]
            status:
              type: object
              required: ["state"]
              default:
                state: ""
                observedGeneration: -1
              properties:
                currentCAPApplicationVersionInstance:
                  type: string
                observedGeneration:
                  type: integer
                state:
                  type: string
                  enum: [ "", "Ready", "Provisioning", "Upgrading", "Deleting", "ProvisioningError", "UpgradeError"]
                lastFullReconciliationTime:
                  type: string
                  format: datetime
                previousCAPApplicationVersions:
                  type: array
                  items:
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status"]
                    properties:
                      type:
                        type: string
                        enum: ["Ready", "Error"]
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastUpdateTime: # Unused property
                        type: string
                        format: datetime
                      lastTransitionTime:
                        type: string
                        format: datetime
                      reason:
                        type: string
                        minLength: 1
                      message:
                        type: string
                      observedGeneration:
                        type: integer
