/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	smesapcomv1alpha1 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubscriptionProviderLister helps list SubscriptionProviders.
// All objects returned here must be treated as read-only.
type SubscriptionProviderLister interface {
	// List lists all SubscriptionProviders in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*smesapcomv1alpha1.SubscriptionProvider, err error)
	// SubscriptionProviders returns an object that can list and get SubscriptionProviders.
	SubscriptionProviders(namespace string) SubscriptionProviderNamespaceLister
	SubscriptionProviderListerExpansion
}

// subscriptionProviderLister implements the SubscriptionProviderLister interface.
type subscriptionProviderLister struct {
	listers.ResourceIndexer[*smesapcomv1alpha1.SubscriptionProvider]
}

// NewSubscriptionProviderLister returns a new SubscriptionProviderLister.
func NewSubscriptionProviderLister(indexer cache.Indexer) SubscriptionProviderLister {
	return &subscriptionProviderLister{listers.New[*smesapcomv1alpha1.SubscriptionProvider](indexer, smesapcomv1alpha1.Resource("subscriptionprovider"))}
}

// SubscriptionProviders returns an object that can list and get SubscriptionProviders.
func (s *subscriptionProviderLister) SubscriptionProviders(namespace string) SubscriptionProviderNamespaceLister {
	return subscriptionProviderNamespaceLister{listers.NewNamespaced[*smesapcomv1alpha1.SubscriptionProvider](s.ResourceIndexer, namespace)}
}

// SubscriptionProviderNamespaceLister helps list and get SubscriptionProviders.
// All objects returned here must be treated as read-only.
type SubscriptionProviderNamespaceLister interface {
	// List lists all SubscriptionProviders in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*smesapcomv1alpha1.SubscriptionProvider, err error)
	// Get retrieves the SubscriptionProvider from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*smesapcomv1alpha1.SubscriptionProvider, error)
	SubscriptionProviderNamespaceListerExpansion
}

// subscriptionProviderNamespaceLister implements the SubscriptionProviderNamespaceLister
// interface.
type subscriptionProviderNamespaceLister struct {
	listers.ResourceIndexer[*smesapcomv1alpha1.SubscriptionProvider]
}
