/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSmeV1alpha2 struct {
	*testing.Fake
}

func (c *FakeSmeV1alpha2) CAPApplications(namespace string) v1alpha2.CAPApplicationInterface {
	return newFakeCAPApplications(c, namespace)
}

func (c *FakeSmeV1alpha2) CAPApplicationVersions(namespace string) v1alpha2.CAPApplicationVersionInterface {
	return newFakeCAPApplicationVersions(c, namespace)
}

func (c *FakeSmeV1alpha2) CAPTenants(namespace string) v1alpha2.CAPTenantInterface {
	return newFakeCAPTenants(c, namespace)
}

func (c *FakeSmeV1alpha2) CAPTenantOperations(namespace string) v1alpha2.CAPTenantOperationInterface {
	return newFakeCAPTenantOperations(c, namespace)
}

func (c *FakeSmeV1alpha2) CAPTenantOutputs(namespace string) v1alpha2.CAPTenantOutputInterface {
	return newFakeCAPTenantOutputs(c, namespace)
}

func (c *FakeSmeV1alpha2) ClusterDomains(namespace string) v1alpha2.ClusterDomainInterface {
	return newFakeClusterDomains(c, namespace)
}

func (c *FakeSmeV1alpha2) Domains(namespace string) v1alpha2.DomainInterface {
	return newFakeDomains(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSmeV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
