/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	typedsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCAPApplicationVersions implements CAPApplicationVersionInterface
type fakeCAPApplicationVersions struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.CAPApplicationVersion, *v1alpha2.CAPApplicationVersionList, *smesapcomv1alpha2.CAPApplicationVersionApplyConfiguration]
	Fake *FakeSmeV1alpha2
}

func newFakeCAPApplicationVersions(fake *FakeSmeV1alpha2, namespace string) typedsmesapcomv1alpha2.CAPApplicationVersionInterface {
	return &fakeCAPApplicationVersions{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.CAPApplicationVersion, *v1alpha2.CAPApplicationVersionList, *smesapcomv1alpha2.CAPApplicationVersionApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("capapplicationversions"),
			v1alpha2.SchemeGroupVersion.WithKind("CAPApplicationVersion"),
			func() *v1alpha2.CAPApplicationVersion { return &v1alpha2.CAPApplicationVersion{} },
			func() *v1alpha2.CAPApplicationVersionList { return &v1alpha2.CAPApplicationVersionList{} },
			func(dst, src *v1alpha2.CAPApplicationVersionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.CAPApplicationVersionList) []*v1alpha2.CAPApplicationVersion {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.CAPApplicationVersionList, items []*v1alpha2.CAPApplicationVersion) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
