/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	typedsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterDomains implements ClusterDomainInterface
type fakeClusterDomains struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.ClusterDomain, *v1alpha2.ClusterDomainList, *smesapcomv1alpha2.ClusterDomainApplyConfiguration]
	Fake *FakeSmeV1alpha2
}

func newFakeClusterDomains(fake *FakeSmeV1alpha2, namespace string) typedsmesapcomv1alpha2.ClusterDomainInterface {
	return &fakeClusterDomains{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.ClusterDomain, *v1alpha2.ClusterDomainList, *smesapcomv1alpha2.ClusterDomainApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("clusterdomains"),
			v1alpha2.SchemeGroupVersion.WithKind("ClusterDomain"),
			func() *v1alpha2.ClusterDomain { return &v1alpha2.ClusterDomain{} },
			func() *v1alpha2.ClusterDomainList { return &v1alpha2.ClusterDomainList{} },
			func(dst, src *v1alpha2.ClusterDomainList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.ClusterDomainList) []*v1alpha2.ClusterDomain {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.ClusterDomainList, items []*v1alpha2.ClusterDomain) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
