/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	typedsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCAPTenants implements CAPTenantInterface
type fakeCAPTenants struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.CAPTenant, *v1alpha2.CAPTenantList, *smesapcomv1alpha2.CAPTenantApplyConfiguration]
	Fake *FakeSmeV1alpha2
}

func newFakeCAPTenants(fake *FakeSmeV1alpha2, namespace string) typedsmesapcomv1alpha2.CAPTenantInterface {
	return &fakeCAPTenants{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.CAPTenant, *v1alpha2.CAPTenantList, *smesapcomv1alpha2.CAPTenantApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("captenants"),
			v1alpha2.SchemeGroupVersion.WithKind("CAPTenant"),
			func() *v1alpha2.CAPTenant { return &v1alpha2.CAPTenant{} },
			func() *v1alpha2.CAPTenantList { return &v1alpha2.CAPTenantList{} },
			func(dst, src *v1alpha2.CAPTenantList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.CAPTenantList) []*v1alpha2.CAPTenant { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha2.CAPTenantList, items []*v1alpha2.CAPTenant) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
