/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	typedsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubscriptionProviders implements SubscriptionProviderInterface
type fakeSubscriptionProviders struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.SubscriptionProvider, *v1alpha2.SubscriptionProviderList, *smesapcomv1alpha2.SubscriptionProviderApplyConfiguration]
	Fake *FakeSmeV1alpha2
}

func newFakeSubscriptionProviders(fake *FakeSmeV1alpha2, namespace string) typedsmesapcomv1alpha2.SubscriptionProviderInterface {
	return &fakeSubscriptionProviders{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.SubscriptionProvider, *v1alpha2.SubscriptionProviderList, *smesapcomv1alpha2.SubscriptionProviderApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("subscriptionproviders"),
			v1alpha2.SchemeGroupVersion.WithKind("SubscriptionProvider"),
			func() *v1alpha2.SubscriptionProvider { return &v1alpha2.SubscriptionProvider{} },
			func() *v1alpha2.SubscriptionProviderList { return &v1alpha2.SubscriptionProviderList{} },
			func(dst, src *v1alpha2.SubscriptionProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.SubscriptionProviderList) []*v1alpha2.SubscriptionProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.SubscriptionProviderList, items []*v1alpha2.SubscriptionProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
