/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	typedsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCAPTenantOperations implements CAPTenantOperationInterface
type fakeCAPTenantOperations struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.CAPTenantOperation, *v1alpha2.CAPTenantOperationList, *smesapcomv1alpha2.CAPTenantOperationApplyConfiguration]
	Fake *FakeSmeV1alpha2
}

func newFakeCAPTenantOperations(fake *FakeSmeV1alpha2, namespace string) typedsmesapcomv1alpha2.CAPTenantOperationInterface {
	return &fakeCAPTenantOperations{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.CAPTenantOperation, *v1alpha2.CAPTenantOperationList, *smesapcomv1alpha2.CAPTenantOperationApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("captenantoperations"),
			v1alpha2.SchemeGroupVersion.WithKind("CAPTenantOperation"),
			func() *v1alpha2.CAPTenantOperation { return &v1alpha2.CAPTenantOperation{} },
			func() *v1alpha2.CAPTenantOperationList { return &v1alpha2.CAPTenantOperationList{} },
			func(dst, src *v1alpha2.CAPTenantOperationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.CAPTenantOperationList) []*v1alpha2.CAPTenantOperation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.CAPTenantOperationList, items []*v1alpha2.CAPTenantOperation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
