/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and cap-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/sap/cap-operator/pkg/apis/sme.sap.com/v1alpha2"
	smesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/applyconfiguration/sme.sap.com/v1alpha2"
	typedsmesapcomv1alpha2 "github.com/sap/cap-operator/pkg/client/clientset/versioned/typed/sme.sap.com/v1alpha2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCAPTenantOutputs implements CAPTenantOutputInterface
type fakeCAPTenantOutputs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha2.CAPTenantOutput, *v1alpha2.CAPTenantOutputList, *smesapcomv1alpha2.CAPTenantOutputApplyConfiguration]
	Fake *FakeSmeV1alpha2
}

func newFakeCAPTenantOutputs(fake *FakeSmeV1alpha2, namespace string) typedsmesapcomv1alpha2.CAPTenantOutputInterface {
	return &fakeCAPTenantOutputs{
		gentype.NewFakeClientWithListAndApply[*v1alpha2.CAPTenantOutput, *v1alpha2.CAPTenantOutputList, *smesapcomv1alpha2.CAPTenantOutputApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha2.SchemeGroupVersion.WithResource("captenantoutputs"),
			v1alpha2.SchemeGroupVersion.WithKind("CAPTenantOutput"),
			func() *v1alpha2.CAPTenantOutput { return &v1alpha2.CAPTenantOutput{} },
			func() *v1alpha2.CAPTenantOutputList { return &v1alpha2.CAPTenantOutputList{} },
			func(dst, src *v1alpha2.CAPTenantOutputList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha2.CAPTenantOutputList) []*v1alpha2.CAPTenantOutput {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha2.CAPTenantOutputList, items []*v1alpha2.CAPTenantOutput) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
