name: Go (Build & Unit test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.21
        cache: true

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build all relevant packages
      run:  CGO_ENABLED=0 go build -v ./cmd/...

    - name: Test relevant packages
      run:  CGO_ENABLED=0 go test -v ./...