name: Publish docker artifacts

on:
  workflow_call:
    inputs:
      workload:
        required: true
        type: string
      sbom:
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  publish-docker:
    name: Publish Docker image
    runs-on: ubuntu-24.04
    permissions:
      contents: write # needed for SBOM upload
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Prepare repository name
      id: prepare-repository-name
      run: |
        repository=$REGISTRY/${{ github.repository }}/${{ inputs.workload }}
        echo "repository=${repository,,}" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: extract-metadata
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=semver,pattern={{version}}
        images: ${{ steps.prepare-repository-name.outputs.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: build/${{ inputs.workload }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        context: .
        cache-from: |
          type=gha,scope=${{ inputs.workload }}-sha-${{ github.sha }}
          type=gha,scope=${{ github.ref_name }}-${{ inputs.workload }}
          type=gha,scope=${{ github.base_ref || 'main' }}
          type=gha,scope=main
        cache-to: |
          type=gha,scope=${{ inputs.workload }}-sha-${{ github.sha }},mode=max
          type=gha,scope=${{ github.ref_name }}-${{ inputs.workload }},mode=max
        push: true
        tags: ${{ steps.extract-metadata.outputs.tags }}
        labels: ${{ steps.extract-metadata.outputs.labels }}
        
    - name: SBOM action (syft)
      if: ${{ inputs.sbom }}
      uses: anchore/sbom-action@v0
      with:
        image: ${{ fromJSON(steps.extract-metadata.outputs.json).tags[0] }}
        format: cyclonedx-json
        artifact-name: ${{ inputs.workload }}-sbom.cyclonedx.json